version: '3.8'

services:
  resume-builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes: # this is needed to mount the volumes, meaning the directories in the container
      - ../:/app # this creates a bind mount from the ../ directory to /app in the container, that makes the files in the container available to the host machine and vice versa
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    command: bash

volumes:
  resume_data:
  resume_logs:

  